# Generated by Django 5.1.6 on 2025-04-27 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_url',
            field=models.URLField(blank=True, help_text='External image URL if not uploading directly', max_length=2000, null=True),
        ),
    ]
