# Generated by Django 5.1.6 on 2025-04-27 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_post_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
